
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSImpMetodosService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8085/WSMetodos?wsdl")
public class WSImpMetodosService
    extends Service
{

    private final static URL WSIMPMETODOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSIMPMETODOSSERVICE_EXCEPTION;
    private final static QName WSIMPMETODOSSERVICE_QNAME = new QName("http://ws/", "WSImpMetodosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/WSMetodos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSIMPMETODOSSERVICE_WSDL_LOCATION = url;
        WSIMPMETODOSSERVICE_EXCEPTION = e;
    }

    public WSImpMetodosService() {
        super(__getWsdlLocation(), WSIMPMETODOSSERVICE_QNAME);
    }

    public WSImpMetodosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSIMPMETODOSSERVICE_QNAME, features);
    }

    public WSImpMetodosService(URL wsdlLocation) {
        super(wsdlLocation, WSIMPMETODOSSERVICE_QNAME);
    }

    public WSImpMetodosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSIMPMETODOSSERVICE_QNAME, features);
    }

    public WSImpMetodosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSImpMetodosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSMetodos
     */
    @WebEndpoint(name = "WSMetodosPort")
    public WSMetodos getWSMetodosPort() {
        return super.getPort(new QName("http://ws/", "WSMetodosPort"), WSMetodos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMetodos
     */
    @WebEndpoint(name = "WSMetodosPort")
    public WSMetodos getWSMetodosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "WSMetodosPort"), WSMetodos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSIMPMETODOSSERVICE_EXCEPTION!= null) {
            throw WSIMPMETODOSSERVICE_EXCEPTION;
        }
        return WSIMPMETODOSSERVICE_WSDL_LOCATION;
    }

}
